### PR TITLE
fix questions post ('text' -> 'input')

### LINKED ISSUE #184: posting questions is broken

### PR DESCRIPTION
**Pull request by duancaro**
fixes #184

### CODE REVIEW

File: server/routes/index.js [hunk 1]
```diff
@@ -281,7 +281,7 @@ router.get('/questions/:unitID', async (req, res) => {
 router.post('/questions', async (req, res) => {
```
Comment (partyshah) [inline server/routes/index.js]: i think you also need to fix the get
