### PR TITLE
yay fixed all back buttons!

### LINKED ISSUE #95: fix all back buttons
needs fixing:
lessons -> units
lesson reflection -> lessons

### PR DESCRIPTION
**Pull request by duancaro**
Fixes #95

### CODE REVIEW

File: client/src/components/LessonReflection/LessonReflection.jsx [hunk 1]
```diff
@@ -1,16 +1,18 @@
...
 import PropTypes from 'prop-types';
-import { NavLink } from 'react-router-dom';
+import { Router } from 'react-router-dom';
+import createBrowserHistory from 'history/createBrowserHistory';
 import { Editor } from '@tinymce/tinymce-react';
 import './LessonReflection.css';
 
 /** Currently Unit ID is hardcoded to 1, should be fetched from API in future versions  */
 const unitID = 1;
+const hst = createBrowserHistory();
```
Comment (partyshah) [inline client/src/components/LessonReflection/LessonReflection.jsx]: create Browser History in App and pass it down as a prop in the routes. You shouldn't create browser history in every component.

File: client/src/components/LessonReflection/LessonReflection.jsx [hunk 2]
```diff
@@ -77,9 +85,11 @@ class LessonReflection extends Component {
     const pathway = `http://localhost:8080${filepath}`;
     return (
       <div>
-        <NavLink to="/lessons" className="Return">
-          &#8592; Return to Lessons
-        </NavLink>
+        <Router history={hst}>
```
Comment (partyshah) [inline client/src/components/LessonReflection/LessonReflection.jsx]: Router should only be in App

File: client/src/components/Units/Units.jsx [hunk 3]
```diff
@@ -1,13 +1,14 @@
 import React, { Component } from 'react';
 import PropTypes from 'prop-types';
 import Modal from 'react-modal';
-import { NavLink } from 'react-router-dom';
+
```
Comment (partyshah) [inline client/src/components/Units/Units.jsx]: delete this space
