### PR TITLE
Fixed routes for classes and units

### LINKED ISSUE #92: Fix routes for classes and units

### PR DESCRIPTION
**Pull request by leebianca**
Fixed #92

### CODE REVIEW

File: client/src/components/Units/Units.jsx [hunk 1]
```diff
@@ -25,6 +25,7 @@ class Units extends Component {
   async componentWillMount() {
     const units = await fetch('/api/units/1');
     const unitsJSON = await units.json();
+    console.log(unitsJSON);
```
Comment (bchee) [inline client/src/components/Units/Units.jsx]: Delete

File: client/src/components/Units/Units.jsx [hunk 2]
```diff
@@ -76,7 +77,7 @@ class Units extends Component {
       this.unitBoxes.push(
         <Unitbox
           unitName={unitNames[i].unit_name}
-          key={unitNames[i].id}
+          id={unitNames[i].id}
```
Comment (bchee) [inline client/src/components/Units/Units.jsx]: Keep this key here but you can add id. Both props are necessary.
