### PR TITLE
fixed something the merge conflict broke

### LINKED ISSUE #178: add new students button doesn't post

### PR DESCRIPTION
**Pull request by duancaro**
fixes #178

### CODE REVIEW

File: server/routes/index.js [hunk 1]
```diff
@@ -36,6 +36,7 @@ async function getUsers(req, res) {
 }
 
 async function setEmails(classID, emails) {
+  console.log('set email');
```
Comment (partyshah) [inline server/routes/index.js]: get rid of all unnecessary console.logs. Also, what was wrong in the first place?

Comment (kelvinjue) [reply server/routes/index.js]: i think something got lost when we were resolving conflicts, so the add students button on the classbox wasn't working properly
